java_tests(name = 'http',
  dependencies = [
    '3rdparty:easymock',
    '3rdparty:jetty',
    '3rdparty:junit',
    'src/java/com/twitter/common/quantity',
    'src/java/com/twitter/common/net/http',
    'src/java/com/twitter/common/testing',
    'src/java/com/twitter/common/util:testing',
  ],
  sources = globs('*.java')
)
